services:
  doc-scanner:
    build:
      context: ./scanner
    image: doc-scanner-image
    container_name: doc_scanner
    hostname: scan-server
    env_file:
      - ./.env
    volumes:
      - ./db:/app/data

#volumes:
#  db:
